services:
  - type: web
    name: pronote-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: node backend/server.js
    plan: free
    envVars:
      - key: PORT
        value: 3001

  - type: web
    name: pronote-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: npx serve -s frontend/dist -l 10000
    plan: free
